keyword = {
  'elif': 'elif',
  'if': 'if',
  'else': 'else',
  'def': 'def',
  'while': 'while',
  'for': 'for',
  'and': 'and',
  'or': 'or',
  'forward': 'method',
  'back': 'method',
  'turnright': 'method',
  'turnleft': 'method',
  'jump': 'method',
  'to_begin': 'method',
  'circle': 'method',
  'speed_up': 'method',
  'speed_down': 'method',
  'undo': 'method',
  'clear': 'method',
  'hide': 'method',
  'penup': 'method',
  'pendown': 'method',
  'leftColor': 'method',
  'rightColor': 'method',
  'getValue': 'method',
  'run': 'method'
}
params_amount = {
    'forward': 0,
    'back': 1,
    'turnright': 0,
    'turnleft': 0,
    'jump': 2,
    'to_begin': 0,
    'circle': 0,
    'speed_up': 1,
    'speed_down': 1,
    'undo': 0,
    'clear': 0,
    'hide': 0,
    'penup': 0,
    'pendown': 0,
    'leftColor': 0,
    'rightColor': 0,
    'getValue': 0,
    'run': 0
}
methods = ["randomRun"]

types = ["Display", "Sensor", "Active"]
